### ISSUE TITLE
Seeing double?

### ISSUE THREAD

**Issue by nicephysics** [nicephysics/game#2]
There seems to be 2 overlapping asteroids...
![image](https://user-images.githubusercontent.com/84841239/125976376-cd092a9e-48de-495d-8ffa-0a0f1e6ba5fc.png)

**Comment by phyzicz** [comment]
Double points also?

**Comment by nicephysics** [comment]
No, it does not give double points... so it is just drawn on the canvas twice.

I will try to solve the problem now.

**Comment by nicephysics** [comment]
Done!
